### ISSUE TITLE
Enabling `numcodecs` on other architectures

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/binpickle-feedstock#11]
It appears that `numcodecs` only gets installed on `x86_64` (as seen below). Likely this preceded `numcodecs` being built on other platforms.

https://github.com/conda-forge/binpickle-feedstock/blob/4f473424b01b01788252aa180eca7ea24ba85345/recipe/meta.yaml#L38-L39

However in PR ( https://github.com/conda-forge/numcodecs-feedstock/pull/76 ), `numcodecs` was enabled on other platforms. This has been around for ~1yr now.

Given this, maybe this selector can be dropped?

**Comment by mdekstrand** [comment]
Thanks! This should also mean I can change `binpickle` to be a `noarch` package, at least if I drop Python 3.7 support.

**Comment by jakirkham** [comment]
As conda-forge has dropped Python 3.7 ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/2623 ), it would be reasonable to drop it from this feedstock unless there was some compelling reason to keep it.

**Comment by mdekstrand** [comment]
@jakirkham thanks! I put a `>=3.8` dep in this feedstock and released as noarch, using `numcodecs` on all platforms.
